### ISSUE TITLE
Create Portuguese translation

### ISSUE THREAD

**Issue by amicloud** [wsmithsrs/SideDeck#15]
According to the Google Play Dev Console statistics, a big portion of users is Brazilian, and I am sure they would appreciate a local translation.

**Comment by rafajaques** [comment]
I can take that. How may I start?

**Comment by amicloud** [comment]
Hi, @rafajaques, thanks for the offer!  I appreciate it, but there is no longer a need, I've already gotten a Brazilian and Regular Portuguese translation made.  This is actually a really old repo, the new (rewritten from the ground up) repo can be found [here](https://github.com/wsmithsrs/SideDeckRewrite).  If you would like to look at the translations and perhaps suggest improvements, the translations are in [this folder](https://github.com/wsmithsrs/SideDeckRewrite/tree/master/app/translations).  

I should've marked all these as closed, my bad
